version: '3.7'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - JWT_SECRET=ae%IiI_43d_hoDop-0w-
    ports:
      - "8080:8080"
    networks:
      - internal
      
networks:
  internal:
    driver: bridge